export enum FederalState {
    BW = 'Baden-Wuerttemberg',
    BY = 'Bayern',
    BE = 'Berlin',
    BB = 'Brandenburg',
    HB = 'Bremen',
    HE = 'Hessen',
    NW = 'Nordrhein-Westfalen',
    NI = 'Niedersachsen',
    SL = 'Saarland',
    HH = 'Hamburg',
    SH = 'Schleswig-Holstein',
    SN = 'Sachsen',
    MV = 'Mecklenburg-Vorpommern',
    RP = 'Rheinland-Pfalz',
    ST = 'Sachsen-Anhalt',
    TH = 'Thueringen',
}
